language: node_js

node_js:
  - '8.12.0'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - 'npm install -g bower grunt-cli'
  - 'npm install'
  - 'bower install'
script: grunt
notifications:
  flowdock:
    secure: QbIGfsj64a2Ms5y/aTO0PUAVBRv9mKxAwLFj5NxWACEVxm1JKZvrQ4ov/8XbVRbRl96sMIoWPox7Gu++ZgLjb7w+jeiCvWLwJwRDxlCgsYvb4hAcPXlNBO7SF4kcUifPfJpaDsb3EThUUK8EtsI5aOxvCqGKMChTDoQnej3kc0o=
sudo: required
dist: trusty

cache:
  directories:
  - $HOME/.m2
